kube:
  config: ~/.kube/config
  resync: 10s
  namespaces:
    - default
    - kube-system

kafka:
  enable: true
  brokers:
    - localhost:9092
    - localhost:9093
  topic: test
  timeout: 10s
  retry: 3
  retryBackoff: 100ms
  flushMsg: 1000
  flushTime: 3s
  flushByte: 1000

elasticsearch:
  enable: false
  address:
    - http://localhost:9200
  user: elastic
  pass: elastic
  index: event

volume:
  enable: true
  fileName: test
  filePath: /tmp
  maxFileSize: 100
  maxFileCount: 10

