kube:
  config: ~/.kube/config
  resync: 10s

kafka:
  brokers:
    - localhost:9092
    - localhost:9093
  topic: test
  timeout: 10s
  retry: 3
  retryBackoff: 100ms
  flushMsg: 1000
  flushTime: 3s
  flushByte: 1000

volume:
  fileName: test
  filePath: /tmp
  maxFileSize: 100
  maxFileCount: 10

