apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: event-clusterrole
rules:
  - apiGroups:
      - events.k8s.io
    resources:
      - events
    verbs: 
      - get
      - list
      - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: event-clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: default
    namespace: event-collector
roleRef:
  kind: ClusterRole
  name: event-clusterrole
  apiGroup: rbac.authorization.k8s.io
