---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: event-sa
  namespace: mytest

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: event-clusterrole
rules:
  - apiGroups:
      - events.k8s.io
    resources:
      - events
    verbs: 
      - get
      - list
      - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: event-clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: event-sa
    namespace: mytest
roleRef:
  kind: ClusterRole
  name: event-clusterrole
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: event-collector-config
  namespace: mytest
data:
  config.yaml: |
    kube:
      namespaces: []
      
    kafka:
      enable: true
      brokers:
        - mytest-kafka-kafka-bootstrap:9092
      topic: event
      timeout: 3s
      retry: 3
      retryBackoff: 100ms
      flushMsg: 1000
      flushTime: 500ms

    elasticsearch:
      enable: true
      addresses:
        - https://elasticsearch-master:9200
      user: "elastic"
      pass: "elastic"
      index: "event"

    volume:
      enable: true
      fileName: event
      filePath: /var/lib/mytest
      maxFileCount: 5

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-collector
  namespace: mytest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-collector
  template:
    metadata:
      labels:
        app: event-collector
    spec:
      serviceAccountName: event-sa
      containers:
        - name: event-collector
          image: event-collector:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: LOG_LEVEL
              value: debug
          volumeMounts:
            - name: config-volume
              mountPath: /etc/collector
      volumes:
        - name: config-volume
          configMap:
            name: event-collector-config